name: E2E tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  e2e_tests:
    strategy:
      matrix:
        # ref: https://github.com/actions/runner-images
        os: [ubuntu-20.04, macos-13]
        lua_version: [5.4.7, 5.3.5]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: install vfox (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/versionfox/ /" | sudo tee /etc/apt/sources.list.d/versionfox.list
          sudo apt-get update
          sudo apt-get install vfox
      
      - name: install vfox (MacOS)
        if: runner.os == 'MacOS'
        run: |
          brew tap version-fox/tap
          brew install vfox

      - name: add vfox-lua plugin
        if: runner.os == 'Windows'
        run: |
          vfox add --source https://github.com/yeshan333/vfox-lua/archive/$env:GITHUB_REF.zip lua

      - name: add vfox-lua plugin
        if: runner.os != 'Windows'
        run: |
          vfox add --source https://github.com/yeshan333/vfox-lua/archive/${GITHUB_REF}.zip lua

      - name: install lua by vfox-lua plugin (Linux)
        if: runner.os == 'Linux'
        env:
          LUA_VERSION: ${{ matrix.lua_version }}
        run: |
          vfox install lua@$LUA_VERSION
          vfox use -g lua@$LUA_VERSION
          eval "$(vfox activate bash)"
          echo "===============PATH==============="
          echo $PATH
          echo "===============PATH==============="
          status=$(lua -v | grep $LUA_VERSION)
          if [ -z "$status" ]; then
            echo "Lua version is not $LUA_VERSION"
            exit 1
          else
            echo "Lua version $LUA_VERSION installed successfully"
          fi

      - name: install lua by vfox-lua plugin (Darwin)
        if: runner.os == 'MacOS'
        env:
          LUA_VERSION: ${{ matrix.lua_version }}
        run: |
          vfox install lua@$LUA_VERSION
          vfox use -g lua@$LUA_VERSION
          eval "$(vfox activate bash)"
          echo "===============PATH==============="
          echo $PATH
          echo "===============PATH==============="
          status=$(lua -v | grep $LUA_VERSION)
          if [ -z "$status" ]; then
            echo "Lua version is not @$LUA_VERSION"
            exit 1
          else
            echo "Lua version $LUA_VERSION installed successfully"
          fi